// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: trefoil/recovery/v1/guardianset.proto

package types

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/cosmos/gogoproto/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Guardianset defines the Guardianset message.
type Guardianset struct {
	Owner     string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Threshold uint64   `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Guardians []string `protobuf:"bytes,3,rep,name=guardians,proto3" json:"guardians,omitempty"`
}

func (m *Guardianset) Reset()         { *m = Guardianset{} }
func (m *Guardianset) String() string { return proto.CompactTextString(m) }
func (*Guardianset) ProtoMessage()    {}
func (*Guardianset) Descriptor() ([]byte, []int) {
	return fileDescriptor_60c2cc9aaf039fc5, []int{0}
}
func (m *Guardianset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Guardianset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Guardianset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Guardianset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Guardianset.Merge(m, src)
}
func (m *Guardianset) XXX_Size() int {
	return m.Size()
}
func (m *Guardianset) XXX_DiscardUnknown() {
	xxx_messageInfo_Guardianset.DiscardUnknown(m)
}

var xxx_messageInfo_Guardianset proto.InternalMessageInfo

func (m *Guardianset) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Guardianset) GetThreshold() uint64 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *Guardianset) GetGuardians() []string {
	if m != nil {
		return m.Guardians
	}
	return nil
}

func init() {
	proto.RegisterType((*Guardianset)(nil), "trefoil.recovery.v1.Guardianset")
}

func init() {
	proto.RegisterFile("trefoil/recovery/v1/guardianset.proto", fileDescriptor_60c2cc9aaf039fc5)
}

var fileDescriptor_60c2cc9aaf039fc5 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2d, 0x29, 0x4a, 0x4d,
	0xcb, 0xcf, 0xcc, 0xd1, 0x2f, 0x4a, 0x4d, 0xce, 0x2f, 0x4b, 0x2d, 0xaa, 0xd4, 0x2f, 0x33, 0xd4,
	0x4f, 0x2f, 0x4d, 0x2c, 0x4a, 0xc9, 0x4c, 0xcc, 0x2b, 0x4e, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x12, 0x86, 0x2a, 0xd3, 0x83, 0x29, 0xd3, 0x2b, 0x33, 0x54, 0x8a, 0xe7, 0xe2, 0x76,
	0x47, 0xa8, 0x14, 0x12, 0xe1, 0x62, 0xcd, 0x2f, 0xcf, 0x4b, 0x2d, 0x92, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x82, 0x70, 0x84, 0x64, 0xb8, 0x38, 0x4b, 0x32, 0x8a, 0x52, 0x8b, 0x33, 0xf2, 0x73,
	0x52, 0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x82, 0x10, 0x02, 0x20, 0x59, 0xb8, 0x65, 0x12, 0xcc,
	0x0a, 0xcc, 0x1a, 0x9c, 0x41, 0x08, 0x01, 0x27, 0xa3, 0x13, 0x8f, 0xe4, 0x18, 0x2f, 0x3c, 0x92,
	0x63, 0x7c, 0xf0, 0x48, 0x8e, 0x71, 0xc2, 0x63, 0x39, 0x86, 0x0b, 0x8f, 0xe5, 0x18, 0x6e, 0x3c,
	0x96, 0x63, 0x88, 0x92, 0x80, 0x39, 0xbb, 0x02, 0xe1, 0xf0, 0x92, 0xca, 0x82, 0xd4, 0xe2, 0x24,
	0x36, 0xb0, 0x83, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xae, 0xa5, 0xb7, 0xd1, 0xd9, 0x00,
	0x00, 0x00,
}

func (m *Guardianset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Guardianset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Guardianset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Guardians) > 0 {
		for iNdEx := len(m.Guardians) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Guardians[iNdEx])
			copy(dAtA[i:], m.Guardians[iNdEx])
			i = encodeVarintGuardianset(dAtA, i, uint64(len(m.Guardians[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.Threshold != 0 {
		i = encodeVarintGuardianset(dAtA, i, uint64(m.Threshold))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintGuardianset(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGuardianset(dAtA []byte, offset int, v uint64) int {
	offset -= sovGuardianset(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Guardianset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovGuardianset(uint64(l))
	}
	if m.Threshold != 0 {
		n += 1 + sovGuardianset(uint64(m.Threshold))
	}
	if len(m.Guardians) > 0 {
		for _, s := range m.Guardians {
			l = len(s)
			n += 1 + l + sovGuardianset(uint64(l))
		}
	}
	return n
}

func sovGuardianset(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGuardianset(x uint64) (n int) {
	return sovGuardianset(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Guardianset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGuardianset
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Guardianset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Guardianset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardianset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuardianset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuardianset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Threshold", wireType)
			}
			m.Threshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardianset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Threshold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Guardians", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardianset
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuardianset
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuardianset
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Guardians = append(m.Guardians, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGuardianset(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGuardianset
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGuardianset(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGuardianset
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGuardianset
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGuardianset
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGuardianset
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGuardianset
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGuardianset
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGuardianset        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGuardianset          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGuardianset = fmt.Errorf("proto: unexpected end of group")
)
