// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: trefoil/recovery/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ece0e376aabe93, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ece0e376aabe93, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryGetGuardiansetRequest defines the QueryGetGuardiansetRequest message.
type QueryGetGuardiansetRequest struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *QueryGetGuardiansetRequest) Reset()         { *m = QueryGetGuardiansetRequest{} }
func (m *QueryGetGuardiansetRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetGuardiansetRequest) ProtoMessage()    {}
func (*QueryGetGuardiansetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ece0e376aabe93, []int{2}
}
func (m *QueryGetGuardiansetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetGuardiansetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetGuardiansetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetGuardiansetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetGuardiansetRequest.Merge(m, src)
}
func (m *QueryGetGuardiansetRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetGuardiansetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetGuardiansetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetGuardiansetRequest proto.InternalMessageInfo

func (m *QueryGetGuardiansetRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

// QueryGetGuardiansetResponse defines the QueryGetGuardiansetResponse message.
type QueryGetGuardiansetResponse struct {
	Guardianset Guardianset `protobuf:"bytes,1,opt,name=guardianset,proto3" json:"guardianset"`
}

func (m *QueryGetGuardiansetResponse) Reset()         { *m = QueryGetGuardiansetResponse{} }
func (m *QueryGetGuardiansetResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetGuardiansetResponse) ProtoMessage()    {}
func (*QueryGetGuardiansetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ece0e376aabe93, []int{3}
}
func (m *QueryGetGuardiansetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetGuardiansetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetGuardiansetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetGuardiansetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetGuardiansetResponse.Merge(m, src)
}
func (m *QueryGetGuardiansetResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetGuardiansetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetGuardiansetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetGuardiansetResponse proto.InternalMessageInfo

func (m *QueryGetGuardiansetResponse) GetGuardianset() Guardianset {
	if m != nil {
		return m.Guardianset
	}
	return Guardianset{}
}

// QueryAllGuardiansetRequest defines the QueryAllGuardiansetRequest message.
type QueryAllGuardiansetRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllGuardiansetRequest) Reset()         { *m = QueryAllGuardiansetRequest{} }
func (m *QueryAllGuardiansetRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllGuardiansetRequest) ProtoMessage()    {}
func (*QueryAllGuardiansetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ece0e376aabe93, []int{4}
}
func (m *QueryAllGuardiansetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllGuardiansetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllGuardiansetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllGuardiansetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllGuardiansetRequest.Merge(m, src)
}
func (m *QueryAllGuardiansetRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllGuardiansetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllGuardiansetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllGuardiansetRequest proto.InternalMessageInfo

func (m *QueryAllGuardiansetRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllGuardiansetResponse defines the QueryAllGuardiansetResponse message.
type QueryAllGuardiansetResponse struct {
	Guardianset []Guardianset       `protobuf:"bytes,1,rep,name=guardianset,proto3" json:"guardianset"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllGuardiansetResponse) Reset()         { *m = QueryAllGuardiansetResponse{} }
func (m *QueryAllGuardiansetResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllGuardiansetResponse) ProtoMessage()    {}
func (*QueryAllGuardiansetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ece0e376aabe93, []int{5}
}
func (m *QueryAllGuardiansetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllGuardiansetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllGuardiansetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllGuardiansetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllGuardiansetResponse.Merge(m, src)
}
func (m *QueryAllGuardiansetResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllGuardiansetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllGuardiansetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllGuardiansetResponse proto.InternalMessageInfo

func (m *QueryAllGuardiansetResponse) GetGuardianset() []Guardianset {
	if m != nil {
		return m.Guardianset
	}
	return nil
}

func (m *QueryAllGuardiansetResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryGetRecoveryRequest defines the QueryGetRecoveryRequest message.
type QueryGetRecoveryRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (m *QueryGetRecoveryRequest) Reset()         { *m = QueryGetRecoveryRequest{} }
func (m *QueryGetRecoveryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRecoveryRequest) ProtoMessage()    {}
func (*QueryGetRecoveryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ece0e376aabe93, []int{6}
}
func (m *QueryGetRecoveryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRecoveryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRecoveryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRecoveryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRecoveryRequest.Merge(m, src)
}
func (m *QueryGetRecoveryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRecoveryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRecoveryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRecoveryRequest proto.InternalMessageInfo

func (m *QueryGetRecoveryRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

// QueryGetRecoveryResponse defines the QueryGetRecoveryResponse message.
type QueryGetRecoveryResponse struct {
	Recovery Recovery `protobuf:"bytes,1,opt,name=recovery,proto3" json:"recovery"`
}

func (m *QueryGetRecoveryResponse) Reset()         { *m = QueryGetRecoveryResponse{} }
func (m *QueryGetRecoveryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRecoveryResponse) ProtoMessage()    {}
func (*QueryGetRecoveryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ece0e376aabe93, []int{7}
}
func (m *QueryGetRecoveryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRecoveryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRecoveryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRecoveryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRecoveryResponse.Merge(m, src)
}
func (m *QueryGetRecoveryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRecoveryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRecoveryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRecoveryResponse proto.InternalMessageInfo

func (m *QueryGetRecoveryResponse) GetRecovery() Recovery {
	if m != nil {
		return m.Recovery
	}
	return Recovery{}
}

// QueryAllRecoveryRequest defines the QueryAllRecoveryRequest message.
type QueryAllRecoveryRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRecoveryRequest) Reset()         { *m = QueryAllRecoveryRequest{} }
func (m *QueryAllRecoveryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllRecoveryRequest) ProtoMessage()    {}
func (*QueryAllRecoveryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ece0e376aabe93, []int{8}
}
func (m *QueryAllRecoveryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRecoveryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRecoveryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRecoveryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRecoveryRequest.Merge(m, src)
}
func (m *QueryAllRecoveryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRecoveryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRecoveryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRecoveryRequest proto.InternalMessageInfo

func (m *QueryAllRecoveryRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllRecoveryResponse defines the QueryAllRecoveryResponse message.
type QueryAllRecoveryResponse struct {
	Recovery   []Recovery          `protobuf:"bytes,1,rep,name=recovery,proto3" json:"recovery"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRecoveryResponse) Reset()         { *m = QueryAllRecoveryResponse{} }
func (m *QueryAllRecoveryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllRecoveryResponse) ProtoMessage()    {}
func (*QueryAllRecoveryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f3ece0e376aabe93, []int{9}
}
func (m *QueryAllRecoveryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRecoveryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRecoveryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRecoveryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRecoveryResponse.Merge(m, src)
}
func (m *QueryAllRecoveryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRecoveryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRecoveryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRecoveryResponse proto.InternalMessageInfo

func (m *QueryAllRecoveryResponse) GetRecovery() []Recovery {
	if m != nil {
		return m.Recovery
	}
	return nil
}

func (m *QueryAllRecoveryResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "trefoil.recovery.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "trefoil.recovery.v1.QueryParamsResponse")
	proto.RegisterType((*QueryGetGuardiansetRequest)(nil), "trefoil.recovery.v1.QueryGetGuardiansetRequest")
	proto.RegisterType((*QueryGetGuardiansetResponse)(nil), "trefoil.recovery.v1.QueryGetGuardiansetResponse")
	proto.RegisterType((*QueryAllGuardiansetRequest)(nil), "trefoil.recovery.v1.QueryAllGuardiansetRequest")
	proto.RegisterType((*QueryAllGuardiansetResponse)(nil), "trefoil.recovery.v1.QueryAllGuardiansetResponse")
	proto.RegisterType((*QueryGetRecoveryRequest)(nil), "trefoil.recovery.v1.QueryGetRecoveryRequest")
	proto.RegisterType((*QueryGetRecoveryResponse)(nil), "trefoil.recovery.v1.QueryGetRecoveryResponse")
	proto.RegisterType((*QueryAllRecoveryRequest)(nil), "trefoil.recovery.v1.QueryAllRecoveryRequest")
	proto.RegisterType((*QueryAllRecoveryResponse)(nil), "trefoil.recovery.v1.QueryAllRecoveryResponse")
}

func init() { proto.RegisterFile("trefoil/recovery/v1/query.proto", fileDescriptor_f3ece0e376aabe93) }

var fileDescriptor_f3ece0e376aabe93 = []byte{
	// 646 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x33, 0xad, 0x8d, 0x76, 0x2a, 0x8a, 0xd3, 0x82, 0x61, 0x6b, 0xb7, 0x61, 0xa4, 0x36,
	0x06, 0xdd, 0x69, 0xd2, 0xbb, 0xd2, 0x1c, 0x8c, 0x07, 0x0f, 0x75, 0xc1, 0x8b, 0x9e, 0x26, 0xe9,
	0xb8, 0x2c, 0x6c, 0x76, 0xb6, 0xbb, 0x9b, 0x68, 0x28, 0x05, 0xf1, 0xe0, 0x59, 0xf4, 0x28, 0x78,
	0x52, 0xf0, 0xd8, 0x3f, 0xa3, 0xc7, 0x82, 0x17, 0x4f, 0x22, 0x89, 0xe0, 0xbf, 0x21, 0x99, 0x7d,
	0xdb, 0xfc, 0x9a, 0xfc, 0x50, 0x7a, 0x09, 0xbb, 0x9b, 0xf7, 0x9d, 0xf7, 0xf9, 0xbe, 0x99, 0xf7,
	0x06, 0x6f, 0xc6, 0xa1, 0x78, 0x29, 0x5d, 0x8f, 0x85, 0xa2, 0x2e, 0x5b, 0x22, 0x6c, 0xb3, 0x56,
	0x89, 0x1d, 0x36, 0x45, 0xd8, 0xb6, 0x82, 0x50, 0xc6, 0x92, 0xac, 0x42, 0x80, 0x95, 0x06, 0x58,
	0xad, 0x92, 0x71, 0x83, 0x37, 0x5c, 0x5f, 0x32, 0xf5, 0x9b, 0xc4, 0x19, 0xc5, 0xba, 0x8c, 0x1a,
	0x32, 0x62, 0x35, 0x1e, 0x89, 0x64, 0x01, 0xd6, 0x2a, 0xd5, 0x44, 0xcc, 0x4b, 0x2c, 0xe0, 0x8e,
	0xeb, 0xf3, 0xd8, 0x95, 0x3e, 0xc4, 0xae, 0x39, 0xd2, 0x91, 0xea, 0x91, 0xf5, 0x9e, 0xe0, 0xeb,
	0x2d, 0x47, 0x4a, 0xc7, 0x13, 0x8c, 0x07, 0x2e, 0xe3, 0xbe, 0x2f, 0x63, 0x25, 0x89, 0xe0, 0xdf,
	0x2d, 0x1d, 0xa8, 0xd3, 0xe4, 0xe1, 0x81, 0xcb, 0xfd, 0x48, 0xc4, 0x10, 0x96, 0xd7, 0x85, 0x05,
	0x3c, 0xe4, 0x8d, 0x74, 0x21, 0xaa, 0x8b, 0x38, 0x37, 0xa7, 0x62, 0xe8, 0x1a, 0x26, 0x4f, 0x7b,
	0x16, 0xf6, 0x95, 0xd0, 0x16, 0x87, 0x4d, 0x11, 0xc5, 0xf4, 0x19, 0x5e, 0x1d, 0xfa, 0x1a, 0x05,
	0xd2, 0x8f, 0x04, 0x79, 0x80, 0xb3, 0x49, 0x82, 0x1c, 0xca, 0xa3, 0xc2, 0x4a, 0x79, 0xdd, 0xd2,
	0x94, 0xcc, 0x4a, 0x44, 0x95, 0xe5, 0xd3, 0x9f, 0x9b, 0x99, 0x6f, 0x7f, 0x4e, 0x8a, 0xc8, 0x06,
	0x15, 0x2d, 0x63, 0x43, 0x2d, 0x5b, 0x15, 0x71, 0xb5, 0xef, 0x07, 0x92, 0x92, 0x35, 0xbc, 0x24,
	0x5f, 0xf9, 0x22, 0x54, 0x8b, 0x2f, 0xdb, 0xc9, 0x0b, 0x75, 0xf0, 0xba, 0x56, 0x03, 0x48, 0x8f,
	0xf1, 0xca, 0x40, 0x69, 0x80, 0x2b, 0xaf, 0xe5, 0x1a, 0x90, 0x57, 0x2e, 0xf5, 0xe0, 0xec, 0x41,
	0x29, 0x3d, 0x00, 0xb8, 0x3d, 0xcf, 0xd3, 0xc0, 0x3d, 0xc2, 0xb8, 0xbf, 0xb9, 0x90, 0xe6, 0x8e,
	0x95, 0x9c, 0x04, 0xab, 0x77, 0x12, 0xac, 0xe4, 0x28, 0xc1, 0x49, 0xb0, 0xf6, 0xb9, 0x23, 0x40,
	0x6b, 0x0f, 0x28, 0xe9, 0x09, 0x02, 0x3f, 0xa3, 0x69, 0x26, 0xf9, 0x59, 0xfc, 0x4f, 0x3f, 0xa4,
	0x3a, 0x44, 0xbc, 0xa0, 0x88, 0xb7, 0x67, 0x12, 0x27, 0x18, 0x43, 0xc8, 0xbb, 0xf8, 0x66, 0xba,
	0x03, 0x36, 0xa4, 0x4f, 0xab, 0x92, 0xc3, 0x97, 0x79, 0xbd, 0x2e, 0x9b, 0x7e, 0x0c, 0x9b, 0x96,
	0xbe, 0xd2, 0x17, 0x38, 0x37, 0x2e, 0x02, 0x8f, 0x0f, 0xf1, 0x95, 0xd4, 0x07, 0x54, 0x72, 0x43,
	0x6b, 0x30, 0x15, 0x82, 0xbb, 0x73, 0x11, 0xe5, 0x40, 0xb4, 0xe7, 0x79, 0xa3, 0x44, 0x17, 0xb5,
	0x4f, 0x5f, 0x10, 0x18, 0x18, 0xca, 0xa1, 0x35, 0xb0, 0xf8, 0xcf, 0x06, 0x2e, 0x6c, 0x6f, 0xca,
	0xef, 0xb2, 0x78, 0x49, 0x61, 0x92, 0x37, 0x08, 0x67, 0x93, 0xce, 0x23, 0xdb, 0x5a, 0x98, 0xf1,
	0x36, 0x37, 0x0a, 0xb3, 0x03, 0x93, 0x9c, 0xf4, 0xf6, 0xdb, 0xef, 0xbf, 0x3f, 0x2e, 0x6c, 0x90,
	0x75, 0x36, 0x79, 0xea, 0x90, 0xaf, 0x08, 0x5f, 0x1b, 0x6e, 0x53, 0xc2, 0x26, 0x67, 0xd0, 0x0e,
	0x01, 0x63, 0x67, 0x7e, 0x01, 0xa0, 0xed, 0x28, 0xb4, 0x22, 0x29, 0xb0, 0x19, 0x73, 0x93, 0x1d,
	0xa9, 0x89, 0x72, 0x4c, 0x3e, 0x23, 0x7c, 0xfd, 0x89, 0x1b, 0xcd, 0x0b, 0xaa, 0x1d, 0x08, 0xd3,
	0x40, 0xf5, 0xad, 0x4d, 0x0b, 0x0a, 0x94, 0x92, 0xfc, 0x2c, 0x50, 0xf2, 0x09, 0xe1, 0x95, 0x81,
	0xc6, 0x21, 0xf7, 0xa6, 0x16, 0x65, 0xa4, 0x05, 0x8c, 0xfb, 0x73, 0x46, 0x03, 0x16, 0x53, 0x58,
	0x77, 0xc9, 0x36, 0x9b, 0x76, 0x5d, 0xb0, 0x23, 0xe8, 0xec, 0x63, 0xf2, 0x01, 0xe1, 0xab, 0xbd,
	0xf2, 0xcd, 0x83, 0x37, 0xde, 0xa1, 0xd3, 0xf0, 0x34, 0xbd, 0x46, 0xb7, 0x14, 0xde, 0x26, 0xd9,
	0x98, 0x8a, 0x57, 0x29, 0x9f, 0x76, 0x4c, 0x74, 0xd6, 0x31, 0xd1, 0xaf, 0x8e, 0x89, 0xde, 0x77,
	0xcd, 0xcc, 0x59, 0xd7, 0xcc, 0xfc, 0xe8, 0x9a, 0x99, 0xe7, 0xb9, 0x54, 0xf7, 0xba, 0xaf, 0x8c,
	0xdb, 0x81, 0x88, 0x6a, 0x59, 0x75, 0x05, 0xee, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x76, 0x31,
	0x43, 0xbb, 0x1a, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// ListGuardianset Queries a list of Guardianset items.
	GetGuardianset(ctx context.Context, in *QueryGetGuardiansetRequest, opts ...grpc.CallOption) (*QueryGetGuardiansetResponse, error)
	// ListGuardianset defines the ListGuardianset RPC.
	ListGuardianset(ctx context.Context, in *QueryAllGuardiansetRequest, opts ...grpc.CallOption) (*QueryAllGuardiansetResponse, error)
	// ListRecovery Queries a list of Recovery items.
	GetRecovery(ctx context.Context, in *QueryGetRecoveryRequest, opts ...grpc.CallOption) (*QueryGetRecoveryResponse, error)
	// ListRecovery defines the ListRecovery RPC.
	ListRecovery(ctx context.Context, in *QueryAllRecoveryRequest, opts ...grpc.CallOption) (*QueryAllRecoveryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/trefoil.recovery.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetGuardianset(ctx context.Context, in *QueryGetGuardiansetRequest, opts ...grpc.CallOption) (*QueryGetGuardiansetResponse, error) {
	out := new(QueryGetGuardiansetResponse)
	err := c.cc.Invoke(ctx, "/trefoil.recovery.v1.Query/GetGuardianset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListGuardianset(ctx context.Context, in *QueryAllGuardiansetRequest, opts ...grpc.CallOption) (*QueryAllGuardiansetResponse, error) {
	out := new(QueryAllGuardiansetResponse)
	err := c.cc.Invoke(ctx, "/trefoil.recovery.v1.Query/ListGuardianset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetRecovery(ctx context.Context, in *QueryGetRecoveryRequest, opts ...grpc.CallOption) (*QueryGetRecoveryResponse, error) {
	out := new(QueryGetRecoveryResponse)
	err := c.cc.Invoke(ctx, "/trefoil.recovery.v1.Query/GetRecovery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListRecovery(ctx context.Context, in *QueryAllRecoveryRequest, opts ...grpc.CallOption) (*QueryAllRecoveryResponse, error) {
	out := new(QueryAllRecoveryResponse)
	err := c.cc.Invoke(ctx, "/trefoil.recovery.v1.Query/ListRecovery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// ListGuardianset Queries a list of Guardianset items.
	GetGuardianset(context.Context, *QueryGetGuardiansetRequest) (*QueryGetGuardiansetResponse, error)
	// ListGuardianset defines the ListGuardianset RPC.
	ListGuardianset(context.Context, *QueryAllGuardiansetRequest) (*QueryAllGuardiansetResponse, error)
	// ListRecovery Queries a list of Recovery items.
	GetRecovery(context.Context, *QueryGetRecoveryRequest) (*QueryGetRecoveryResponse, error)
	// ListRecovery defines the ListRecovery RPC.
	ListRecovery(context.Context, *QueryAllRecoveryRequest) (*QueryAllRecoveryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetGuardianset(ctx context.Context, req *QueryGetGuardiansetRequest) (*QueryGetGuardiansetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGuardianset not implemented")
}
func (*UnimplementedQueryServer) ListGuardianset(ctx context.Context, req *QueryAllGuardiansetRequest) (*QueryAllGuardiansetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGuardianset not implemented")
}
func (*UnimplementedQueryServer) GetRecovery(ctx context.Context, req *QueryGetRecoveryRequest) (*QueryGetRecoveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecovery not implemented")
}
func (*UnimplementedQueryServer) ListRecovery(ctx context.Context, req *QueryAllRecoveryRequest) (*QueryAllRecoveryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRecovery not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trefoil.recovery.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetGuardianset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetGuardiansetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetGuardianset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trefoil.recovery.v1.Query/GetGuardianset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetGuardianset(ctx, req.(*QueryGetGuardiansetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListGuardianset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllGuardiansetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListGuardianset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trefoil.recovery.v1.Query/ListGuardianset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListGuardianset(ctx, req.(*QueryAllGuardiansetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetRecovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRecoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetRecovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trefoil.recovery.v1.Query/GetRecovery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetRecovery(ctx, req.(*QueryGetRecoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListRecovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllRecoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListRecovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/trefoil.recovery.v1.Query/ListRecovery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListRecovery(ctx, req.(*QueryAllRecoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "trefoil.recovery.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetGuardianset",
			Handler:    _Query_GetGuardianset_Handler,
		},
		{
			MethodName: "ListGuardianset",
			Handler:    _Query_ListGuardianset_Handler,
		},
		{
			MethodName: "GetRecovery",
			Handler:    _Query_GetRecovery_Handler,
		},
		{
			MethodName: "ListRecovery",
			Handler:    _Query_ListRecovery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trefoil/recovery/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetGuardiansetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetGuardiansetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetGuardiansetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetGuardiansetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetGuardiansetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetGuardiansetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Guardianset.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllGuardiansetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllGuardiansetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllGuardiansetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllGuardiansetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllGuardiansetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllGuardiansetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Guardianset) > 0 {
		for iNdEx := len(m.Guardianset) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Guardianset[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRecoveryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRecoveryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRecoveryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRecoveryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRecoveryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRecoveryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Recovery.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllRecoveryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRecoveryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRecoveryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRecoveryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRecoveryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRecoveryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Recovery) > 0 {
		for iNdEx := len(m.Recovery) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Recovery[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetGuardiansetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetGuardiansetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Guardianset.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllGuardiansetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllGuardiansetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Guardianset) > 0 {
		for _, e := range m.Guardianset {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRecoveryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRecoveryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Recovery.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllRecoveryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRecoveryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Recovery) > 0 {
		for _, e := range m.Recovery {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetGuardiansetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetGuardiansetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetGuardiansetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetGuardiansetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetGuardiansetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetGuardiansetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Guardianset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Guardianset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllGuardiansetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllGuardiansetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllGuardiansetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllGuardiansetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllGuardiansetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllGuardiansetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Guardianset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Guardianset = append(m.Guardianset, Guardianset{})
			if err := m.Guardianset[len(m.Guardianset)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRecoveryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRecoveryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRecoveryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRecoveryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRecoveryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRecoveryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recovery", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Recovery.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRecoveryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRecoveryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRecoveryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRecoveryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRecoveryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRecoveryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recovery", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recovery = append(m.Recovery, Recovery{})
			if err := m.Recovery[len(m.Recovery)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
