// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: trefoil/recovery/v1/recovery.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Recovery defines the Recovery message.
type Recovery struct {
	Account     string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Newaddress  string   `protobuf:"bytes,2,opt,name=newaddress,proto3" json:"newaddress,omitempty"`
	Requester   string   `protobuf:"bytes,3,opt,name=requester,proto3" json:"requester,omitempty"`
	Approvals   []string `protobuf:"bytes,4,rep,name=approvals,proto3" json:"approvals,omitempty"`
	Requestedat int64    `protobuf:"varint,5,opt,name=requestedat,proto3" json:"requestedat,omitempty"`
	Executeat   int64    `protobuf:"varint,6,opt,name=executeat,proto3" json:"executeat,omitempty"`
}

func (m *Recovery) Reset()         { *m = Recovery{} }
func (m *Recovery) String() string { return proto.CompactTextString(m) }
func (*Recovery) ProtoMessage()    {}
func (*Recovery) Descriptor() ([]byte, []int) {
	return fileDescriptor_81c82fc367ed20d6, []int{0}
}
func (m *Recovery) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Recovery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Recovery.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Recovery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recovery.Merge(m, src)
}
func (m *Recovery) XXX_Size() int {
	return m.Size()
}
func (m *Recovery) XXX_DiscardUnknown() {
	xxx_messageInfo_Recovery.DiscardUnknown(m)
}

var xxx_messageInfo_Recovery proto.InternalMessageInfo

func (m *Recovery) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *Recovery) GetNewaddress() string {
	if m != nil {
		return m.Newaddress
	}
	return ""
}

func (m *Recovery) GetRequester() string {
	if m != nil {
		return m.Requester
	}
	return ""
}

func (m *Recovery) GetApprovals() []string {
	if m != nil {
		return m.Approvals
	}
	return nil
}

func (m *Recovery) GetRequestedat() int64 {
	if m != nil {
		return m.Requestedat
	}
	return 0
}

func (m *Recovery) GetExecuteat() int64 {
	if m != nil {
		return m.Executeat
	}
	return 0
}

func init() {
	proto.RegisterType((*Recovery)(nil), "trefoil.recovery.v1.Recovery")
}

func init() {
	proto.RegisterFile("trefoil/recovery/v1/recovery.proto", fileDescriptor_81c82fc367ed20d6)
}

var fileDescriptor_81c82fc367ed20d6 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x63, 0x02, 0x85, 0x9a, 0xcd, 0x2c, 0x37, 0x20, 0xcb, 0xea, 0xd4, 0xa9, 0x55, 0xe1,
	0x0d, 0x78, 0x84, 0x8c, 0x6c, 0xc6, 0x39, 0x24, 0xa4, 0xaa, 0x36, 0xe7, 0x8b, 0x69, 0xdf, 0x82,
	0x47, 0x62, 0x64, 0xec, 0xc8, 0x88, 0x92, 0x17, 0xa9, 0x62, 0x35, 0x49, 0xb7, 0xfb, 0xbf, 0xef,
	0xbf, 0xe5, 0x97, 0x0b, 0x26, 0x7c, 0xf7, 0x1f, 0xdb, 0x35, 0xa1, 0xf3, 0x09, 0xe9, 0xb0, 0x4e,
	0x9b, 0xf1, 0x5e, 0x05, 0xf2, 0xec, 0xd5, 0xc3, 0xb9, 0xb3, 0x1a, 0x79, 0xda, 0x2c, 0x7e, 0x84,
	0xbc, 0xab, 0xce, 0x59, 0x81, 0xbc, 0xb5, 0xce, 0xf9, 0x66, 0xc7, 0x20, 0x8c, 0x58, 0xce, 0xab,
	0x21, 0x2a, 0x2d, 0xe5, 0x0e, 0xbf, 0x6c, 0x5d, 0x13, 0xc6, 0x08, 0x57, 0x59, 0x5e, 0x10, 0xf5,
	0x28, 0xe7, 0x84, 0x9f, 0x0d, 0x46, 0x46, 0x82, 0x32, 0xeb, 0x09, 0xf4, 0xd6, 0x86, 0x40, 0x3e,
	0xd9, 0x6d, 0x84, 0x6b, 0x53, 0xf6, 0x76, 0x04, 0xca, 0xc8, 0xfb, 0xa1, 0x5a, 0x5b, 0x86, 0x1b,
	0x23, 0x96, 0x65, 0x75, 0x89, 0xfa, 0x7f, 0xdc, 0xa3, 0x6b, 0x18, 0x2d, 0xc3, 0x2c, 0xfb, 0x09,
	0xbc, 0x3c, 0xfd, 0xb6, 0x5a, 0x1c, 0x5b, 0x2d, 0xfe, 0x5b, 0x2d, 0xbe, 0x3b, 0x5d, 0x1c, 0x3b,
	0x5d, 0xfc, 0x75, 0xba, 0x78, 0x85, 0x61, 0x95, 0xfd, 0xb4, 0x0b, 0x1f, 0x02, 0xc6, 0xb7, 0x59,
	0x9e, 0xe4, 0xf9, 0x14, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x0d, 0x22, 0x1e, 0x38, 0x01, 0x00, 0x00,
}

func (m *Recovery) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Recovery) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Recovery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Executeat != 0 {
		i = encodeVarintRecovery(dAtA, i, uint64(m.Executeat))
		i--
		dAtA[i] = 0x30
	}
	if m.Requestedat != 0 {
		i = encodeVarintRecovery(dAtA, i, uint64(m.Requestedat))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Approvals) > 0 {
		for iNdEx := len(m.Approvals) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Approvals[iNdEx])
			copy(dAtA[i:], m.Approvals[iNdEx])
			i = encodeVarintRecovery(dAtA, i, uint64(len(m.Approvals[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Requester) > 0 {
		i -= len(m.Requester)
		copy(dAtA[i:], m.Requester)
		i = encodeVarintRecovery(dAtA, i, uint64(len(m.Requester)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Newaddress) > 0 {
		i -= len(m.Newaddress)
		copy(dAtA[i:], m.Newaddress)
		i = encodeVarintRecovery(dAtA, i, uint64(len(m.Newaddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintRecovery(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintRecovery(dAtA []byte, offset int, v uint64) int {
	offset -= sovRecovery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Recovery) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovRecovery(uint64(l))
	}
	l = len(m.Newaddress)
	if l > 0 {
		n += 1 + l + sovRecovery(uint64(l))
	}
	l = len(m.Requester)
	if l > 0 {
		n += 1 + l + sovRecovery(uint64(l))
	}
	if len(m.Approvals) > 0 {
		for _, s := range m.Approvals {
			l = len(s)
			n += 1 + l + sovRecovery(uint64(l))
		}
	}
	if m.Requestedat != 0 {
		n += 1 + sovRecovery(uint64(m.Requestedat))
	}
	if m.Executeat != 0 {
		n += 1 + sovRecovery(uint64(m.Executeat))
	}
	return n
}

func sovRecovery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRecovery(x uint64) (n int) {
	return sovRecovery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Recovery) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRecovery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Recovery: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Recovery: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Newaddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Newaddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requester", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Requester = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Approvals", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRecovery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRecovery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Approvals = append(m.Approvals, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Requestedat", wireType)
			}
			m.Requestedat = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Requestedat |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Executeat", wireType)
			}
			m.Executeat = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Executeat |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRecovery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRecovery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRecovery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRecovery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRecovery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRecovery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRecovery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRecovery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRecovery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRecovery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRecovery = fmt.Errorf("proto: unexpected end of group")
)
