syntax = "proto3";

package trefoil.recovery.v1;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "trefoil/recovery/v1/guardianset.proto";
import "trefoil/recovery/v1/params.proto";
import "trefoil/recovery/v1/recovery.proto";

option go_package = "trefoil/x/recovery/types";

// GenesisState defines the recovery module's genesis state.
message GenesisState {
  // params defines all the parameters of the module.
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  repeated Guardianset guardianset_map = 2 [(gogoproto.nullable) = false];
  repeated Recovery recovery_map = 3 [(gogoproto.nullable) = false];
}
