syntax = "proto3";

package trefoil.recovery.v1;

import "amino/amino.proto";
import "cosmos/base/query/v1beta1/pagination.proto";
import "gogoproto/gogo.proto";
import "google/api/annotations.proto";
import "trefoil/recovery/v1/guardianset.proto";
import "trefoil/recovery/v1/params.proto";
import "trefoil/recovery/v1/recovery.proto";

option go_package = "trefoil/x/recovery/types";

// Query defines the gRPC querier service.
service Query {
  // Parameters queries the parameters of the module.
  rpc Params(QueryParamsRequest) returns (QueryParamsResponse) {
    option (google.api.http).get = "/trefoil/recovery/v1/params";
  }

  // ListGuardianset Queries a list of Guardianset items.
  rpc GetGuardianset(QueryGetGuardiansetRequest) returns (QueryGetGuardiansetResponse) {
    option (google.api.http).get = "/trefoil/recovery/v1/guardianset/{owner}";
  }

  // ListGuardianset defines the ListGuardianset RPC.
  rpc ListGuardianset(QueryAllGuardiansetRequest) returns (QueryAllGuardiansetResponse) {
    option (google.api.http).get = "/trefoil/recovery/v1/guardianset";
  }

  // ListRecovery Queries a list of Recovery items.
  rpc GetRecovery(QueryGetRecoveryRequest) returns (QueryGetRecoveryResponse) {
    option (google.api.http).get = "/trefoil/recovery/v1/recovery/{account}";
  }

  // ListRecovery defines the ListRecovery RPC.
  rpc ListRecovery(QueryAllRecoveryRequest) returns (QueryAllRecoveryResponse) {
    option (google.api.http).get = "/trefoil/recovery/v1/recovery";
  }
}
// QueryParamsRequest is request type for the Query/Params RPC method.
message QueryParamsRequest {}

// QueryParamsResponse is response type for the Query/Params RPC method.
message QueryParamsResponse {
  // params holds all the parameters of this module.
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}

// QueryGetGuardiansetRequest defines the QueryGetGuardiansetRequest message.
message QueryGetGuardiansetRequest {
  string owner = 1;
}

// QueryGetGuardiansetResponse defines the QueryGetGuardiansetResponse message.
message QueryGetGuardiansetResponse {
  Guardianset guardianset = 1 [(gogoproto.nullable) = false];
}

// QueryAllGuardiansetRequest defines the QueryAllGuardiansetRequest message.
message QueryAllGuardiansetRequest {
  cosmos.base.query.v1beta1.PageRequest pagination = 1;
}

// QueryAllGuardiansetResponse defines the QueryAllGuardiansetResponse message.
message QueryAllGuardiansetResponse {
  repeated Guardianset guardianset = 1 [(gogoproto.nullable) = false];
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}

// QueryGetRecoveryRequest defines the QueryGetRecoveryRequest message.
message QueryGetRecoveryRequest {
  string account = 1;
}

// QueryGetRecoveryResponse defines the QueryGetRecoveryResponse message.
message QueryGetRecoveryResponse {
  Recovery recovery = 1 [(gogoproto.nullable) = false];
}

// QueryAllRecoveryRequest defines the QueryAllRecoveryRequest message.
message QueryAllRecoveryRequest {
  cosmos.base.query.v1beta1.PageRequest pagination = 1;
}

// QueryAllRecoveryResponse defines the QueryAllRecoveryResponse message.
message QueryAllRecoveryResponse {
  repeated Recovery recovery = 1 [(gogoproto.nullable) = false];
  cosmos.base.query.v1beta1.PageResponse pagination = 2;
}
